### ISSUE TITLE
Cannot sort by nullable fileds

### ISSUE THREAD

**Issue by ciprianm** [mrahhal/MR.AspNetCore.Pagination#4]
Great library, it's been working great for us until we ran into this issue when trying to sort by a nullable field:

```
The binary operator GreaterThan is not defined for the types 'System.Nullable`1[System.Int32]' and 'System.Int32'

at System.Linq.Expressions.Expression.GetUserDefinedBinaryOperatorOrThrow(ExpressionType binaryType, String name, Expression left, Expression right, Boolean liftToNull)
at System.Linq.Expressions.Expression.GetComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
at System.Linq.Expressions.Expression.GreaterThan(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
at System.Linq.Expressions.Expression.GreaterThan(Expression left, Expression right)
at MR.EntityFrameworkCore.KeysetPagination.KeysetPaginationExtensions.MakeComparisonExpression[T](KeysetPaginationItem`1 item, MemberExpression memberAccess, ConstantExpression referenceValue, Func`3 compare)
at MR.EntityFrameworkCore.KeysetPagination.KeysetPaginationExtensions.BuildKeysetFilterPredicateExpression[T](IReadOnlyList`1 items, KeysetPaginationDirection direction, Object reference)
at MR.EntityFrameworkCore.KeysetPagination.KeysetPaginationExtensions.HasAsync[T](KeysetPaginationContext`1 context, KeysetPaginationDirection direction, Object reference)
at MR.EntityFrameworkCore.KeysetPagination.KeysetPaginationExtensions.HasPreviousAsync[T,T2](KeysetPaginationContext`1 context, IReadOnlyList`1 data)
at MR.AspNetCore.Pagination.PaginationService.KeysetPaginateAsync[T,TOut](IQueryable`1 source, Action`1 builderAction, Func`2 getReferenceAsync, Func`2 map, Nullable`1 pageSize)
at Kelverion.AutomationPortal.Api.Persistence.Repository.OfferingRepository.ListOfferingAsync(OfferingQuery query, IQueryable`1 offeringsQuery) 
```

My model class. The property ItemParentId corresponds to a nullable DB field.

```
public class Offering
{
  public int Id { get; set; }
  public int? ItemParentId { get; set; }
  ...
}
```

Calling keyset pagination this way:

```
var result = await PaginationService.KeysetPaginateAsync(
  Context.Offerings,
  builder => builder.Descending(o => o.ItemParentId).Ascending(o => o.Id),
  async id => await Context.Offerings.FindAsync(id),
  query.PageSize);
```

Am I doing something wrong?

**Comment by mrahhal** [comment]
Ah, I think I know what's going on. Will look into this today.

**Comment by ciprianm** [comment]
Thanks. Quick check shows this to be fixed. Will test more thoroughly next week and let you know if I run into issues.
